import { v4 as uuidv4 } from 'uuid'

import { BracketStatus } from '@/Common/Components/BracketDetails/BracketForm.types'
import { GenericStatus, EventData } from '@/Common/Common.types'
import { MatchPlayRoundStatus } from '@/Common/Components/TournamentDetails/TournamentForm.types'

export const createEventMockData: EventData = {
  brackets: [
    {
      activeRound: 0,
      age: 'Adults',
      areTeamsEnabled: false,
      basedOnPercent: 0,
      basedOnScore: 0,
      bracketNumPlayers: 8,
      bracketScoringType: 'Standard',
      bracketType: 'Singles',
      bracketWebs: [],
      dates: '2023-04-28',
      description: 'An 8-man singles scratch bowling bracket',
      entryFee: 10,
      firstPayout: 25,
      fourthPayout: 0,
      houseCut: 2,
      id: 'B1',
      isHandicap: false,
      location: 'All lanes',
      loserBrackets: [],
      name: 'Singles Scratch Bracket',
      numLanes: 60,
      playerCount: 0,
      prizes: '20, 15',
      rules: 'USBC Bracket Rules',
      secondPayout: 10,
      sport: 'Bowling',
      status: BracketStatus.Not_Shuffled,
      teamCount: 0,
      thirdPayout: 0,
    },
    {
      age: 'Adults',
      id: 'B2',
      name: 'Singles Handicap Bracket',
      sport: 'Bowling',
      description: 'An 8-man singles handicap bowling bracket',
      rules: 'USBC Bracket Rules',
      location: 'All lanes',
      dates: '2023-04-28',
      bracketScoringType: 'Standard',
      bracketType: 'Singles',
      bracketNumPlayers: 8,
      firstPayout: 25,
      fourthPayout: 0,
      isHandicap: true,
      basedOnPercent: 90,
      basedOnScore: 220,
      areTeamsEnabled: false,
      entryFee: 10,
      houseCut: 2,
      loserBrackets: [],
      prizes: '20, 15',
      numLanes: 60,
      secondPayout: 10,
      status: BracketStatus.Not_Shuffled,
      bracketWebs: [],
      activeRound: 0,
      playerCount: 0,
      teamCount: 0,
      thirdPayout: 0,
    },
    // {
    //   id: 'B3',
    //   name: 'Reverse Scratch Bracket',
    //   sport: 'Bowling',
    //   description: 'A reverse scratch bowling bracket',
    //   rules: 'USBC Bracket Rules',
    //   location: 'All lanes',
    //   dates: '2023-04-28',
    //   bracketScoringType: 'Reverse',
    //   bracketType: 'Singles',
    //   bracketNumPlayers: 8,
    //   firstPayout: 25,
    //   fourthPayout: 0,
    //   isHandicap: false,
    //   basedOnPercent: 0,
    //   basedOnScore: 0,
    //   areTeamsEnabled: false,
    //   entryFee: 10,
    //   age: 'Adults',
    //   houseCut: 2,
    //   loserBrackets: [],
    //   prizes: '20, 15',
    //   numLanes: 60,
    //   secondPayout: 10,
    //   status: BracketStatus.Not_Shuffled,
    //   bracketWebs: [],
    //   activeRound: 0,
    //   playerCount: 0,
    //   teamCount: 0,
    //   thirdPayout: 0,
    // },
    // {
    //   id: 'B4',
    //   name: 'Reverse Handicap Bracket',
    //   sport: 'Bowling',
    //   description: 'A reverse handicap bowling bracket',
    //   rules: 'USBC Bracket Rules',
    //   location: 'All lanes',
    //   dates: '2023-04-28',
    //   bracketScoringType: 'Reverse',
    //   bracketType: 'Singles',
    //   bracketNumPlayers: 8,
    //   firstPayout: 25,
    //   fourthPayout: 0,
    //   isHandicap: true,
    //   basedOnPercent: 90,
    //   basedOnScore: 220,
    //   areTeamsEnabled: false,
    //   entryFee: 10,
    //   age: 'Adults',
    //   houseCut: 2,
    //   loserBrackets: [],
    //   prizes: '20, 15',
    //   numLanes: 60,
    //   secondPayout: 10,
    //   status: BracketStatus.Not_Shuffled,
    //   bracketWebs: [],
    //   activeRound: 0,
    //   playerCount: 0,
    //   teamCount: 0,
    //   thirdPayout: 0,
    // },
    {
      id: 'B5',
      name: 'Team Scratch Bracket',
      sport: 'Bowling',
      description: 'A team scratch bowling bracket',
      rules: 'USBC Bracket Rules',
      location: 'All lanes',
      dates: '2023-04-28',
      bracketScoringType: 'Standard',
      bracketType: 'Teams',
      bracketNumPlayers: 8,
      firstPayout: 25,
      fourthPayout: 0,
      isHandicap: false,
      basedOnPercent: 0,
      basedOnScore: 0,
      areTeamsEnabled: true,
      entryFee: 10,
      age: 'Adults',
      houseCut: 2,
      loserBrackets: [],
      prizes: '20, 15',
      numLanes: 60,
      secondPayout: 10,
      status: BracketStatus.Not_Shuffled,
      bracketWebs: [],
      activeRound: 0,
      playerCount: 0,
      teamCount: 0,
      thirdPayout: 0,
    },
    {
      id: 'B6',
      name: 'Team Handicap Bracket',
      sport: 'Bowling',
      description: 'A team handicap bowling bracket',
      rules: 'USBC Bracket Rules',
      location: 'All lanes',
      dates: '2023-04-28',
      bracketScoringType: 'Standard',
      bracketType: 'Teams',
      bracketNumPlayers: 8,
      firstPayout: 25,
      fourthPayout: 0,
      isHandicap: true,
      basedOnPercent: 90,
      basedOnScore: 220,
      areTeamsEnabled: true,
      entryFee: 10,
      age: 'Adults',
      houseCut: 2,
      loserBrackets: [],
      prizes: '20, 15',
      numLanes: 60,
      secondPayout: 10,
      status: BracketStatus.Not_Shuffled,
      bracketWebs: [],
      activeRound: 0,
      playerCount: 0,
      teamCount: 0,
      thirdPayout: 0,
    },
    // {
    //   id: 'B7',
    //   name: 'Eliminator Scratch Bracket',
    //   sport: 'Bowling',
    //   description: 'An eliminator scratch bowling bracket',
    //   rules: 'USBC Bracket Rules',
    //   location: 'All lanes',
    //   dates: '2023-04-28',
    //   bracketScoringType: 'Standard',
    //   bracketType: 'Eliminator',
    //   bracketNumPlayers: 8,
    //   firstPayout: 25,
    //   fourthPayout: 0,
    //   isHandicap: false,
    //   basedOnPercent: 0,
    //   basedOnScore: 0,
    //   areTeamsEnabled: false,
    //   entryFee: 10,
    //   age: 'Adults',
    //   houseCut: 2,
    //   loserBrackets: [],
    //   prizes: '20, 15',
    //   numLanes: 60,
    //   secondPayout: 10,
    //   status: BracketStatus.Not_Shuffled,
    //   bracketWebs: [],
    //   activeRound: 0,
    //   playerCount: 0,
    //   teamCount: 0,
    //   thirdPayout: 0,
    // },
    // {
    //   id: 'B8',
    //   name: 'Eliminator Handicap Bracket',
    //   sport: 'Bowling',
    //   description: 'An eliminator handicap bowling bracket',
    //   rules: 'USBC Bracket Rules',
    //   location: 'All lanes',
    //   dates: '2023-04-28',
    //   bracketScoringType: 'Standard',
    //   bracketType: 'Eliminator',
    //   bracketNumPlayers: 8,
    //   firstPayout: 25,
    //   fourthPayout: 0,
    //   isHandicap: true,
    //   basedOnPercent: 90,
    //   basedOnScore: 220,
    //   areTeamsEnabled: false,
    //   entryFee: 10,
    //   age: 'Adults',
    //   houseCut: 2,
    //   loserBrackets: [],
    //   prizes: '20, 15',
    //   numLanes: 60,
    //   secondPayout: 10,
    //   status: BracketStatus.Not_Shuffled,
    //   bracketWebs: [],
    //   activeRound: 0,
    //   playerCount: 0,
    //   teamCount: 0,
    //   thirdPayout: 0,
    // },
    // {
    //   id: 'B9',
    //   name: '4 Man Scratch Bracket',
    //   sport: 'Bowling',
    //   description: 'A 4-Man scratch bowling bracket',
    //   rules: 'USBC Bracket Rules',
    //   location: 'All lanes',
    //   dates: '2023-04-28',
    //   bracketScoringType: 'Standard',
    //   bracketType: 'Singles',
    //   bracketNumPlayers: 4,
    //   firstPayout: 25,
    //   fourthPayout: 0,
    //   isHandicap: false,
    //   basedOnPercent: 0,
    //   basedOnScore: 0,
    //   areTeamsEnabled: false,
    //   entryFee: 10,
    //   age: 'Adults',
    //   houseCut: 2,
    //   loserBrackets: [],
    //   prizes: '20, 15',
    //   numLanes: 60,
    //   secondPayout: 10,
    //   status: BracketStatus.Not_Shuffled,
    //   bracketWebs: [],
    //   activeRound: 0,
    //   playerCount: 0,
    //   teamCount: 0,
    //   thirdPayout: 0,
    // },
    // {
    //   id: 'B10',
    //   name: '2 Man Scratch Bracket',
    //   sport: 'Bowling',
    //   description: 'A 2-Man scratch bowling bracket',
    //   rules: 'USBC Bracket Rules',
    //   location: 'All lanes',
    //   dates: '2023-04-28',
    //   bracketScoringType: 'Standard',
    //   bracketType: 'Singles',
    //   bracketNumPlayers: 2,
    //   firstPayout: 25,
    //   fourthPayout: 0,
    //   isHandicap: false,
    //   basedOnPercent: 0,
    //   basedOnScore: 0,
    //   areTeamsEnabled: false,
    //   entryFee: 10,
    //   age: 'Adults',
    //   houseCut: 2,
    //   loserBrackets: [],
    //   prizes: '20, 15',
    //   numLanes: 60,
    //   secondPayout: 10,
    //   status: BracketStatus.Not_Shuffled,
    //   bracketWebs: [],
    //   activeRound: 0,
    //   playerCount: 0,
    //   teamCount: 0,
    //   thirdPayout: 0,
    // },
    // {
    //   id: 'B11',
    //   name: 'Double Elimination Singles Scratch Bracket',
    //   sport: 'Bowling',
    //   description: 'A double elimination scratch bowling bracket',
    //   rules: 'USBC Bracket Rules',
    //   location: 'All lanes',
    //   dates: '2023-04-28',
    //   bracketScoringType: 'Standard',
    //   bracketType: 'Double Elimination Singles',
    //   bracketNumPlayers: 16,
    //   firstPayout: 20,
    //   fourthPayout: 2,
    //   isHandicap: false,
    //   basedOnPercent: 0,
    //   basedOnScore: 0,
    //   areTeamsEnabled: false,
    //   entryFee: 10,
    //   age: 'Adults',
    //   houseCut: 2,
    //   loserBrackets: [],
    //   prizes: '20, 15',
    //   numLanes: 60,
    //   secondPayout: 8,
    //   status: BracketStatus.Not_Shuffled,
    //   bracketWebs: [],
    //   activeRound: 0,
    //   playerCount: 0,
    //   teamCount: 0,
    //   thirdPayout: 5,
    // },
  ],
  eventDetails: {
    areNotificationsEnabled: true,
    createdAt: new Date().toISOString(),
    date: '2023-04-28',
    description:
      'This is a huge bowling event the likes of which have never been seen before. Do you feel lucky?',
    directorInfo: {
      email: 'fake@fake.com',
      name: 'John Smith',
      phone: '123-456-7890',
    },
    id: uuidv4(),
    isPrivate: false,
    generatorsEnabled: false,
    location: 'Lucky 7 Lanes',
    name: 'Lucky 7 Main Event',
    numParticipants: 0,
    paymentLink: 'www.testpaymentlink.com/this-is-fake-do-not-use/',
    photo: null,
    status: GenericStatus.Open,
  },
  games: [
    {
      id: uuidv4(),
      status: GenericStatus.Open,
      name: 'Game 1',
      tournaments: [
        {
          id: 'T1',
          roundNum: '1',
        },
        {
          id: 'T2',
          roundNum: '1',
        },
        {
          id: 'T3',
          roundNum: '1',
        },
        {
          id: 'T4',
          roundNum: '1',
        },
        {
          id: 'T5',
          roundNum: '1',
        },
        {
          id: 'T6',
          roundNum: '1',
        },
        {
          id: 'T7',
          roundNum: '1',
        },
        {
          id: 'T8',
          roundNum: '1',
        },
        {
          id: 'T9',
          roundNum: '1',
        },
        {
          id: 'T10',
          roundNum: '1',
        },
      ],
      leagues: [],
      brackets: [
        {
          id: 'B1',
          roundNum: '1',
        },
        {
          id: 'B2',
          roundNum: '1',
        },
        {
          id: 'B3',
          roundNum: '3',
        },
        {
          id: 'B4',
          roundNum: '3',
        },
        {
          id: 'B5',
          roundNum: '1',
        },
        {
          id: 'B6',
          roundNum: '1',
        },
        {
          id: 'B7',
          roundNum: '1',
        },
        {
          id: 'B8',
          roundNum: '1',
        },
        {
          id: 'B9',
          roundNum: '1',
        },
        {
          id: 'B10',
          roundNum: '1',
        },
        {
          id: 'B11',
          roundNum: '1',
        },
      ],
    },
    {
      id: uuidv4(),
      status: GenericStatus.Open,
      name: 'Game 2',
      tournaments: [
        {
          id: 'T1',
          roundNum: '2',
        },
        {
          id: 'T2',
          roundNum: '2',
        },
        {
          id: 'T3',
          roundNum: '2',
        },
        {
          id: 'T4',
          roundNum: '2',
        },
        {
          id: 'T5',
          roundNum: '2',
        },
        {
          id: 'T6',
          roundNum: '2',
        },
        {
          id: 'T7',
          roundNum: '2',
        },
        {
          id: 'T8',
          roundNum: '2',
        },
        {
          id: 'T9',
          roundNum: '2',
        },
        {
          id: 'T10',
          roundNum: '2',
        },
      ],
      leagues: [],
      brackets: [
        {
          id: 'B1',
          roundNum: '2',
        },
        {
          id: 'B2',
          roundNum: '2',
        },
        {
          id: 'B3',
          roundNum: '2',
        },
        {
          id: 'B4',
          roundNum: '2',
        },
        {
          id: 'B5',
          roundNum: '2',
        },
        {
          id: 'B6',
          roundNum: '2',
        },
        {
          id: 'B7',
          roundNum: '2',
        },
        {
          id: 'B8',
          roundNum: '2',
        },
        {
          id: 'B9',
          roundNum: '2',
        },
        {
          id: 'B11',
          roundNum: '2',
        },
      ],
    },
    {
      id: uuidv4(),
      status: GenericStatus.Open,
      name: 'Game 3',
      tournaments: [
        {
          id: 'T1',
          roundNum: '3',
        },
        {
          id: 'T2',
          roundNum: '3',
        },
        {
          id: 'T3',
          roundNum: '3',
        },
        {
          id: 'T4',
          roundNum: '3',
        },
        {
          id: 'T5',
          roundNum: '3',
        },
        {
          id: 'T6',
          roundNum: '3',
        },
        {
          id: 'T7',
          roundNum: '3',
        },
        {
          id: 'T8',
          roundNum: '3',
        },
        {
          id: 'T9',
          roundNum: '3',
        },
        {
          id: 'T10',
          roundNum: '3',
        },
      ],
      leagues: [],
      brackets: [
        {
          id: 'B1',
          roundNum: '3',
        },
        {
          id: 'B2',
          roundNum: '3',
        },
        {
          id: 'B3',
          roundNum: '1',
        },
        {
          id: 'B4',
          roundNum: '1',
        },
        {
          id: 'B5',
          roundNum: '3',
        },
        {
          id: 'B6',
          roundNum: '3',
        },
        {
          id: 'B7',
          roundNum: '3',
        },
        {
          id: 'B8',
          roundNum: '3',
        },
        {
          id: 'B11',
          roundNum: '3',
        },
      ],
    },
    {
      id: uuidv4(),
      status: GenericStatus.Open,
      name: 'Game 4',
      tournaments: [
        {
          id: 'T8',
          roundNum: '4',
        },
      ],
      leagues: [],
      brackets: [
        {
          id: 'B11',
          roundNum: '4',
        },
      ],
    },
  ],
  generators: [],
  guestPlayers: [],
  leagues: [],
  players: [],
  scores: [],
  teams: [],
  tournaments: [
    // {
    //   age: 'Adult',
    //   areTeamsEnabled: false,
    //   basedOnPercent: 0,
    //   basedOnScore: 0,
    //   dates: '2023-04-28',
    //   description: 'A singles scratch bowling tournament',
    //   entryFee: 10,
    //   houseCut: 2,
    //   id: 'T1',
    //   isHandicap: false,
    //   isMixed: false,
    //   isOpen: true,
    //   location: 'All lanes',
    //   matchPlayInfo: [],
    //   name: 'Singles Scratch Tournament',
    //   numLanes: 60,
    //   numRounds: 3,
    //   playerCount: 0,
    //   prizes: '20, 15',
    //   rules: 'USBC Tournament Rules',
    //   sidePots: {
    //     highPot: { enabled: false, enrollmentFee: 0 },
    //     lowPot: { enabled: false, enrollmentFee: 0 },
    //   },
    //   sport: 'Bowling',
    //   teamCount: 0,
    //   teamWinners: [],
    //   tournamentType: 'Singles',
    //   winners: [],
    // },
    // {
    //   age: 'Adult',
    //   areTeamsEnabled: false,
    //   basedOnPercent: 90,
    //   basedOnScore: 220,
    //   dates: '2023-04-28',
    //   description: 'A singles handicap bowling tournament',
    //   entryFee: 10,
    //   houseCut: 2,
    //   id: 'T2',
    //   isHandicap: true,
    //   isMixed: false,
    //   isOpen: true,
    //   location: 'All lanes',
    //   matchPlayInfo: [],
    //   name: 'Singles Handicap Tournament',
    //   numLanes: 60,
    //   numRounds: 3,
    //   playerCount: 0,
    //   prizes: '20, 15',
    //   rules: 'USBC Tournament Rules',
    //   sidePots: {
    //     highPot: { enabled: false, enrollmentFee: 0 },
    //     lowPot: { enabled: false, enrollmentFee: 0 },
    //   },
    //   sport: 'Bowling',
    //   teamCount: 0,
    //   teamWinners: [],
    //   tournamentType: 'Singles',
    //   winners: [],
    // },
    // {
    //   age: 'Adult',
    //   areTeamsEnabled: false,
    //   basedOnPercent: 0,
    //   basedOnScore: 0,
    //   dates: '2023-04-28',
    //   description: 'A singles round robin scratch bowling tournament',
    //   entryFee: 10,
    //   houseCut: 2,
    //   id: 'T3',
    //   isHandicap: false,
    //   isMixed: false,
    //   isOpen: true,
    //   location: 'All lanes',
    //   matchPlayInfo: [],
    //   name: 'Round Robin Singles Scratch Tournament',
    //   numLanes: 60,
    //   numRounds: 3,
    //   playerCount: 0,
    //   prizes: '20, 15',
    //   rules: 'USBC Tournament Rules',
    //   sidePots: {
    //     highPot: { enabled: false, enrollmentFee: 0 },
    //     lowPot: { enabled: false, enrollmentFee: 0 },
    //   },
    //   sport: 'Bowling',
    //   teamCount: 0,
    //   teamWinners: [],
    //   tournamentType: 'Round Robin Singles',
    //   winners: [],
    // },
    // {
    //   dates: '2023-04-28',
    //   description: 'A round robin handicap bowling tournament',
    //   id: 'T4',
    //   isHandicap: true,
    //   location: 'All lanes',
    //   matchPlayInfo: [],
    //   name: 'Round Robin Singles Handicap Tournament',
    //   numRounds: 3,
    //   rules: 'USBC Tournament Rules',
    //   sidePots: {
    //     highPot: { enabled: false, enrollmentFee: 0 },
    //     lowPot: { enabled: false, enrollmentFee: 0 },
    //   },
    //   sport: 'Bowling',
    //   tournamentType: 'Round Robin Singles',
    //   basedOnPercent: 90,
    //   basedOnScore: 220,
    //   areTeamsEnabled: false,
    //   isMixed: false,
    //   entryFee: 10,
    //   age: 'Adult',
    //   houseCut: 2,
    //   prizes: '20, 15',
    //   numLanes: 60,
    //   isOpen: true,
    //   winners: [],
    //   teamWinners: [],
    //   playerCount: 0,
    //   teamCount: 0,
    // },
    // {
    //   id: 'T5',
    //   name: 'Round Robin Singles Mixed Scratch Tournament',
    //   sport: 'Bowling',
    //   description: 'A round robin scratch bowling tournament',
    //   rules: 'USBC Tournament Rules',
    //   location: 'All lanes',
    //   matchPlayInfo: [],
    //   dates: '2023-04-28',
    //   numRounds: 3,
    //   sidePots: {
    //     highPot: { enabled: false, enrollmentFee: 0 },
    //     lowPot: { enabled: false, enrollmentFee: 0 },
    //   },
    //   tournamentType: 'Round Robin Singles',
    //   isHandicap: false,
    //   basedOnPercent: 0,
    //   basedOnScore: 0,
    //   areTeamsEnabled: false,
    //   isMixed: true,
    //   entryFee: 10,
    //   age: 'Adult',
    //   houseCut: 2,
    //   prizes: '20, 15',
    //   numLanes: 60,
    //   isOpen: true,
    //   winners: [],
    //   teamWinners: [],
    //   playerCount: 0,
    //   teamCount: 0,
    // },
    {
      id: 'T6',
      name: 'Teams Scratch Tournament',
      sport: 'Bowling',
      description: 'A team scratch bowling tournament',
      rules: 'USBC Tournament Rules',
      location: 'All lanes',
      matchPlayInfo: [],
      dates: '2023-04-28',
      numRounds: 3,
      sidePots: {
        highPot: { enabled: false, enrollmentFee: 0 },
        lowPot: { enabled: false, enrollmentFee: 0 },
      },
      tournamentType: 'Teams',
      isHandicap: false,
      basedOnPercent: 0,
      basedOnScore: 0,
      areTeamsEnabled: true,
      isMixed: false,
      entryFee: 10,
      age: 'Adult',
      houseCut: 2,
      prizes: '20, 15',
      numLanes: 60,
      isOpen: true,
      winners: [],
      teamWinners: [],
      playerCount: 0,
      teamCount: 0,
    },
    {
      id: 'T7',
      name: 'Teams Handicap Tournament',
      sport: 'Bowling',
      description: 'A team handicap bowling tournament',
      rules: 'USBC Tournament Rules',
      location: 'All lanes',
      matchPlayInfo: [],
      dates: '2023-04-28',
      numRounds: 3,
      sidePots: {
        highPot: { enabled: false, enrollmentFee: 0 },
        lowPot: { enabled: false, enrollmentFee: 0 },
      },
      tournamentType: 'Teams',
      isHandicap: true,
      basedOnPercent: 90,
      basedOnScore: 220,
      areTeamsEnabled: true,
      isMixed: false,
      entryFee: 10,
      age: 'Adult',
      houseCut: 2,
      prizes: '20, 15',
      numLanes: 60,
      isOpen: true,
      winners: [],
      teamWinners: [],
      playerCount: 0,
      teamCount: 0,
    },
    // {
    //   age: 'Adult',
    //   areTeamsEnabled: false,
    //   basedOnPercent: 0,
    //   basedOnScore: 0,
    //   dates: '2023-04-28',
    //   description: 'A Scratch Match Play bowling tournament',
    //   entryFee: 10,
    //   houseCut: 2,
    //   id: 'T8',
    //   isHandicap: false,
    //   isMixed: false,
    //   isOpen: true,
    //   location: 'All lanes',
    //   matchPlayInfo: [
    //     {
    //       matchUps: [],
    //       numGames: 3,
    //       scoringType: 'Point',
    //       status: MatchPlayRoundStatus.Open,
    //     },
    //     {
    //       matchUps: [],
    //       numGames: 1,
    //       scoringType: 'Point',
    //       status: MatchPlayRoundStatus.Open,
    //     },
    //   ],
    //   name: 'Match Play Tournament',
    //   numLanes: 60,
    //   numRounds: 2,
    //   playerCount: 0,
    //   prizes: '20, 15',
    //   rules: 'USBC Tournament Rules',
    //   sidePots: {
    //     highPot: { enabled: false, enrollmentFee: 0 },
    //     lowPot: { enabled: false, enrollmentFee: 0 },
    //   },
    //   sport: 'Bowling',
    //   teamCount: 0,
    //   teamWinners: [],
    //   tournamentType: 'Match Play Singles',
    //   winners: [],
    // },
    {
      age: 'Adult',
      areTeamsEnabled: false,
      basedOnPercent: 0,
      basedOnScore: 0,
      dates: '2023-04-28',
      description: 'A scratch bowling tournament with pots',
      entryFee: 10,
      houseCut: 2,
      id: 'T9',
      isHandicap: false,
      isMixed: false,
      isOpen: true,
      location: 'All lanes',
      matchPlayInfo: [],
      name: 'Scratch Tournament w/Pots',
      numLanes: 60,
      numRounds: 3,
      playerCount: 0,
      prizes: '20, 15',
      rules: 'USBC Tournament Rules',
      sidePots: {
        highPot: { enabled: true, enrollmentFee: 5 },
        lowPot: { enabled: true, enrollmentFee: 5 },
      },
      sport: 'Bowling',
      teamCount: 0,
      teamWinners: [],
      tournamentType: 'Singles',
      winners: [],
    },
    {
      age: 'Adult',
      areTeamsEnabled: false,
      basedOnPercent: 90,
      basedOnScore: 220,
      dates: '2023-04-28',
      description: 'A handicap bowling tournament with Pots',
      entryFee: 10,
      houseCut: 2,
      id: 'T10',
      isHandicap: true,
      isMixed: false,
      isOpen: true,
      location: 'All lanes',
      matchPlayInfo: [],
      name: 'Handicap Tournament w/Pots',
      numLanes: 60,
      numRounds: 3,
      playerCount: 0,
      prizes: '20, 15',
      rules: 'USBC Tournament Rules',
      sidePots: {
        highPot: { enabled: true, enrollmentFee: 5 },
        lowPot: { enabled: true, enrollmentFee: 5 },
      },
      sport: 'Bowling',
      teamCount: 0,
      teamWinners: [],
      tournamentType: 'Singles',
      winners: [],
    },
  ],
}
